
'use client';

import { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Team, teamSchema } from '@/lib/data';
import { useToast } from '@/hooks/use-toast';
import {
  useFirestore,
  setDocumentNonBlocking,
  updateDocumentNonBlocking,
} from '@/firebase';
import { collection, doc } from 'firebase/firestore';
import { z } from 'zod';

// We omit the ID for the form schema, as it's generated by Firestore
const formSchema = teamSchema.omit({ id: true });

type TeamFormValues = z.infer<typeof formSchema>;

interface TeamFormProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  team: Team | null;
}

export function TeamForm({ open, onOpenChange, team }: TeamFormProps) {
  const { toast } = useToast();
  const firestore = useFirestore();
  const isEditMode = !!team;

  const form = useForm<TeamFormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      name: '',
      department: '',
    },
  });

  useEffect(() => {
    if (team) {
      form.reset({
        name: team.name,
        department: team.department,
      });
    } else {
      form.reset({
        name: '',
        department: '',
      });
    }
  }, [team, form]);

  const onSubmit = (data: TeamFormValues) => {
    if (!firestore) return;

    if (isEditMode && team) {
      const teamRef = doc(firestore, 'teams', team.id);
      updateDocumentNonBlocking(teamRef, data);
    } else {
      // Create a new document reference with a generated ID
      const newTeamRef = doc(collection(firestore, 'teams'));
      const newTeamData = { ...data, id: newTeamRef.id };
      setDocumentNonBlocking(newTeamRef, newTeamData, {});
    }

    toast({
      title: 'Success!',
      description: `Team has been ${isEditMode ? 'updated' : 'created'}.`,
    });
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{isEditMode ? 'Edit' : 'Add New'} Team</DialogTitle>
          <DialogDescription>
            Fill out the form below to{' '}
            {isEditMode ? 'update the' : 'create a new'} team.
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <FormField
              control={form.control}
              name="name"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Team Name</FormLabel>
                  <FormControl>
                    <Input
                      placeholder="e.g., Parking Facilities"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="department"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Department</FormLabel>
                  <FormControl>
                    <Input
                      placeholder="e.g., Transportation and Mobility"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <DialogFooter>
              <Button
                type="button"
                variant="outline"
                onClick={() => onOpenChange(false)}
              >
                Cancel
              </Button>
              <Button type="submit">{isEditMode ? 'Update' : 'Create'}</Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
